{{- if .Values.namespace }}
{{- if ne .Values.namespace "default" }}
# Create training namespace if it doesn't exist
# Note: In production, namespace is usually pre-created by cluster admin
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "training-infrastructure.labels" . | nindent 4 }}
    purpose: ml-training
{{- end }}
{{- end }}
