[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.ultralytics"

[deploy]
startCommand = "python /workspace/training/api_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
